### ISSUE TITLE
Converter generates C# structs that do not compile when C struct is self referencing.

### ISSUE THREAD

**Issue by jmaine** [microsoft/ClangSharp#146] opened 2020-06-16 07:31 UTC
The converter generates C# structs that do not compile when C struct is self-referencing.

This should be fixed because many C structs use this design when building linked lists.
Example input:  
```C
typedef struct example_s example_t;

struct example_s {
   example_t       *next;
  void *data;
};
```
Example output:  
```C#
   public unsafe partial struct example_s
    {
        [NativeTypeName("example_t *")]
        public example_s* next;
        
        public void* data;
   }
```
The expected output should be something that compiles in C# without modification and without casts (preferably).

**Comment by tannergooding** [comment] 2020-06-16 15:34
Could you please clarify the issue. This exact example case works as expected: https://github.com/microsoft/ClangSharp/pull/147

**Comment by jmaine** [comment] 2020-06-17 05:24
It seems that the generator is creating references to types that are not being generated which are located in /usr/include/ or its subdirectories.

**Comment by tannergooding** [comment] 2020-06-17 14:12
That is expected. By default, the binding generator only traverses the main file and you must explicitly opt into other files if they should be traversed as well.

If this wasn't done, then you would get binding generation for a large chunk of the C runtime with nearly any header you processed. This is generally undesirable, makes the code less portable, and ends up covering quite a bit of templated and other scenarios that might not be trivially handled by the generator today.

**Comment by tannergooding** [comment] 2021-03-21 22:58
Closing as this behavior is currently by design. Additional files need to be explicitly added to the traversal list.

**Closed by tannergooding** 2021-03-21 22:58 UTC
